# corppa configuration
# copy this file to corppa_config.yml and edit as needed

# local path to compiled poem dataset files
poem_dataset:
  # NOTE: currently requires an absolute path, since jupyter
  # notebooks will try to load relative to the notebook
  data_dir: "/path/to/ppa-found-poems/data/"

# paths to data and metadata for
reference_corpora:
  internet_poems:
    data_path: path/to/internet-poems/
  chadwyck-healey:
    data_path: path/to/chadwyck-healey/
    metadata_path: path/to/chadwyck-healey_metadata.csv
  other_poems:
    # url for google sheets as CSV
    metadata_url:
