# Copyright (c) 2024-2025, Center for Digital Humanities, Princeton University
# SPDX-License-Identifier: Apache-2.0

# corppa configuration for automated tests / continuous integration

# local path to compiled poem dataset files
poem_dataset:
  # Use relative path for CI, since the path depends on the build.
  # For notebooks, relative path starts from the notebook directory.
  data_dir: "sample_data/"
