# Copyright (c) 2024-2025, Center for Digital Humanities, Princeton University
# SPDX-License-Identifier: Apache-2.0

# corppa configuration for automated tests / continuous integration
base_dir: .

# local path to compiled poem dataset files
# Use relative path for CI, since the path depends on the build.
# For notebooks, relative path starts from the notebook directory.
compiled_dataset_dir: sample_data

