name: Check jupyter notebooks

on:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: .

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          # uses .python-version if not specified

      - name: Install package with notebook dependencies
        run: uv sync --extra notebooks

      # copy notebook config file to current directory
      - name: Check jupyter notebooks with treon
        run: cp notebooks/sample_data/test_config.yml ./corppa_config.yml

      # run treon to confirm that notebooks run with current code
      - name: Check jupyter notebooks with treon
        run: uv run treon notebooks/excerpt_overlap_review.ipynb notebooks/poetry_excerpt_review.ipynb
